version: '2'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password

  azkexec:
    image: rinscy/azkaban-execserver:3.1.0
    environment:
      - MYSQL_HOST=mysql
    ports:
      - "12321:12321"

  azkweb:
      image: rinscy/azkaban-webserver:3.1.0
      environment:
        - MYSQL_HOST=mysql
        - MYSQL_ROOT_PASSWORD=password
      ports:
        - "8081:8081"
